### ISSUE TITLE
Play back of recordings does not work

### ISSUE THREAD

**Issue by marmay** [ta264/Emby.MythTv#4]
When trying to play back a recording, I get a couple of exceptions. The strange thing is that I can't see any outputs by the plugin. Is the media information put into the database for all recordings and the plugin is not called each time I click the play button?

I am on Debian stretch running the current stable version of emby. Play back of LiveTV works.

C# is not my primary language, but I think that, eventually, I can track that problem down myself, if you can't reproduce it easily. In order to save time, any help on where to start is appreciated, of course.

Btw, I can't install the plugin on the dev-channel of emby. Has the API been changed?

Log after  pressing the play button is attached.
[error_log.txt](https://github.com/ta264/Emby.MythTv/files/620283/error_log.txt)

**Comment by ta264** [comment]
Can you try with v1.0.1 I just pushed please?  Not sure what your issue is but these are some fixes I had locally.

In plugin settings, what do you have as the "Recordings UNC"?  The help text needs updating, it should be the local folder where mythtv's recordings are.  For me, it's `/mnt/data/mythtv`

If that still doesn't work, please can you restart emby, try to play a recording and then attach the full log file?

I think emby does "store" the recordings in the library once it's seen them, so if something has gone wrong you might need to regenerate your library.

**Comment by marmay** [comment]
Thank you for your help; I did not set up the Recordings UNC correctly. After fixing it, I also removed all recording-related entries from the emby library. I don't know whether this was necessary. Probably not.

Then it seemed that it did not work at first. But after playing around a bit old recordings started to work; I thought this was about the change from .mpg (in MythTV 0.27) to .ts in MythTV 0.28, but then I noticed that emby was probing those recordings for some information (bitrate, contained streams) and that playback would not work before this was completed.

By the way, I stayed with version 1.0.0 while debugging that issue. I am installing 1.0.1 now.
